#!/usr/bin/env python3
"""Fix the two things Astro's generated _redirects cannot do for this host.

Runs as part of `npm run build`, so `npm run deploy` cannot ship without it.

1. Percent-encode non-ASCII source paths
--------------------------------------
Astro writes redirect sources exactly as `redirects.json` holds them, which for
the one URL that matters is raw UTF-8 Hebrew:

    /מכתב-התראה-מעורך-דין-.../    /articles/demand-letter-guide/    301

Cloudflare matches `_redirects` against the **percent-encoded** request path. A
browser or crawler sends `/%D7%9E%D7%9B%D7%AA%D7%91-...`, which never equals the
raw form, so the rule silently did nothing and the URL 404'd. Verified against
the live response, not assumed.

`redirects.json` deliberately keeps the readable form: the sitemap filter in
`astro.config.mjs` compares against a *decoded* pathname, so encoding at source
would quietly let redirect sources back into the sitemap.

2. Make the trailing-slash redirect permanent
---------------------------------------------
The site is `trailingSlash: 'always'`. Cloudflare's static-asset router adds the
slash itself, but it answers **307 Temporary Redirect** and there is no setting
that changes that — `html_handling: "force-trailing-slash"` was tried and
measured, and still returned 307.

A 307 tells Google the move is temporary, so it keeps the slashless URL in the
index and passes no authority to the real page. That is what produced the
"Page with redirect" notice in Search Console on 9 Aug 2026.

Explicit rules in `_redirects` are matched before the router's automatic
handling, so writing them as 301 wins. One rule per built page, generated from
the build output so a new page can never be forgotten.

TESTING NOTE: `curl` sends a raw UTF-8 path verbatim, which no browser does.
Testing the unencoded form reports 404 on a redirect that works perfectly.
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist" / "client"
REDIRECTS = DIST / "_redirects"

# Everything legal in a path that must survive untouched. quote() already
# leaves unreserved characters alone; this keeps the separators too.
SAFE = "/-_.~!$&'()*+,;=:@%"


def encode(path: str) -> str:
    return path if path.isascii() else quote(path, safe=SAFE)


def built_pages() -> list[str]:
    """Every directory-style URL the build produced, e.g. /about/."""
    out = []
    for p in DIST.rglob("index.html"):
        rel = p.relative_to(DIST).parent.as_posix()
        if rel != ".":
            out.append(f"/{rel}/")
    return sorted(out)


def main() -> None:
    if not REDIRECTS.exists():
        sys.exit(f"{REDIRECTS} not found — run `npm run build` first.")

    lines = REDIRECTS.read_text(encoding="utf-8").splitlines()

    kept: list[str] = []
    existing_sources: set[str] = set()
    encoded = 0

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            kept.append(line)
            continue

        parts = line.split()
        if len(parts) < 2:
            kept.append(line)
            continue

        src = parts[0]
        if not src.isascii():
            parts[0] = encode(src)
            encoded += 1
            kept.append(f"{parts[0]}  {'  '.join(parts[1:])}")
        else:
            kept.append(line)

        existing_sources.add(parts[0])
        # A rule for `/foo/` also needs `/foo` covered; record the bare form so
        # the generated block below does not contradict a hand-written rule.
        existing_sources.add(parts[0].rstrip("/") or "/")

    # ---- trailing-slash rules, one per built page -------------------------
    slash_rules: list[str] = []
    for page in built_pages():
        bare = encode(page.rstrip("/"))
        if not bare or bare in existing_sources:
            continue
        slash_rules.append(f"{bare}  {encode(page)}  301")

    out = list(kept)
    if slash_rules:
        out += [
            "",
            "# Slashless -> canonical, written explicitly as 301.",
            "# Cloudflare's asset router adds the slash on its own but answers 307,",
            "# which Google treats as temporary: it keeps the slashless URL indexed",
            "# and passes no authority through. Generated by",
            "# scripts/postprocess-redirects.py from the build output.",
            *slash_rules,
        ]

    REDIRECTS.write_text("\n".join(out) + "\n", encoding="utf-8")

    print(
        f"[redirects] {encoded} source path(s) percent-encoded, "
        f"{len(slash_rules)} trailing-slash 301(s) written"
    )


if __name__ == "__main__":
    main()
